apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc   
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb:3306  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest  
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_ROOT_PASSWORD
          value: ''
        - name: MYSQL_DATABASE
          value: wordpress
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql   
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc  

        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html   
