# Define default values for Jenkins deployment
replicaCount: 1
image:
  repository: jenkins/jenkins
  tag: 2.289.1-lts-jdk11
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
ingress:
  enabled: true
  path: /jenkins
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
