appName: wp-app

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: 
    # Add specific annotations as needed for your Ingress controller
  hosts:
    - host: "application_gateway_public_ip" 
      paths:
        - path: "/jenkins/"
          pathType: Prefix