apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName }}
  namespace: default
  labels:
    app: {{.Values.appName }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: jenkins
      tier: frontend
  template:
    metadata:
      labels:
        app: {{.Values.appName }}
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: elonetwork/webapp:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: myconfigmapv1.0
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"