apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080  # Port on which your service runs
      targetPort: 8080  # Port your service listens on
  selector:
    app: jenkins  # Label selector for your Jenkins pods
