apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: eloacrprd.azurecr.io/0.001:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "test"
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/stretchshop_demo"  # Update MongoDB connection details
