apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: your-acr-name.azurecr.io/wordpress-image:latest  # Replace with your ACR image path
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "wordpress"  # Replace with your MariaDB service name in Kubernetes
            - name: WORDPRESS_DB_USER
              value: "root"  # Replace with your database username
            - name: WORDPRESS_DB_PASSWORD
              value: "SeddinePass**"  # Replace with your database password
            - name: WORDPRESS_DB_NAME
              value: "wordpress"  # Replace with your database name
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wordpress
