apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.env.WORDPRESS_DB_HOST }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.env.WORDPRESS_DB_USER }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.wordpress.env.WORDPRESS_DB_PASSWORD }}
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
  selector:
    app: wordpress
