apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
  selector:
    app: wordpress